export * from './MovieList/MovieList';
export * from './MovieCard/MovieCard';
export * from './Header/Header'
export * from './SearchForm/SearchForm';
export * from './FilterMovie/FilterMovie';
export * from './MovieInfo/MovieInfo';
export * from './FormYear/FormYear';
export * from './PersonPage/PersonPage';
export * from './Person/Person';
export * from './PersonInfo/PersonInfo';
export  * from './SearchPage/SearchPage';
export  * from './YearPage/YearPage';
export * from './Menu/Menu'